version: '3.8'

services:
  app:
    image: demoapp:latest
    ports:
      - "8080:8080"
    environment:
      JWT_GENERATOR_SIGNATURE_SECRET: ${JWT_GENERATOR_SIGNATURE_SECRET}
      JWT_GENERATOR_SIGNATURE_SECRET_REFRESH: ${JWT_GENERATOR_SIGNATURE_SECRET}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: ${DB_URL}
    command:
      - sleep 3
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_DB}
    ports:
      - "55432:5432"
