micronaut:
  application:
    name: demoapp
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET}"'
        generator:
          refresh-token:
            enabled: true
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET_REFRESH}"'
          access-token:
            expiration: ${TOKEN_EXPIRATION}
  server:
    netty:
      access-logger:
        enabled: true

datasources:
  default:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

flyway:
  datasources:
    default:
      enabled: true
